config/routes.rb
Rails.application.routes.draw do
root to: 'homes#top'
  resources :books
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 
   
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
 class BooksController < ApplicationController
  def index
    @book=Book.new
    @books=Book.all
     
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
   @book = Book.new(book_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
    # 4. トップ画面へリダイレクト
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
  
    else  
      @books=Book.all
      render :index
    
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   @book.update(book_params)
    
    if @book.save
                      
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path
    else @books=Book.all
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end
  def destroy
     book = Book.find(params[:id])
     book.destroy  # データ（レコード）を削除
     redirect_to '/books'
  end

   private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booker_helper.rb
module BookerHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

  <span>
    <%= link_to "show", book_path(@book.id)%>
  </span>

  <span>
    <%= link_to "Back", books_path%>
  </span>

<% end %>

app/views/books/index.html.erb
<h2>Books</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<table>
<thead>
  <tr>
    <th>Title</th>

   <th>Body</th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>

  <td><%= book.title %></td>

  <td><%= book.body %></td>
  <td><%= link_to "show", book_path(book.id)%> </td>
  <td>  <%= link_to "Edit", edit_book_path(book.id)%></td>
 <td>  <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
</td>

</tr>
<% end %>
</tbody>
</table>

<h2>New book</h2>
<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>Title</h4>

  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>


<% end %>

app/views/books/show.html.erb
<div><%= flash[:notice] %></div>
<h2>Title</h2>
<p><%= @book.title %></p>

<h2>Body</h2>
<p><%= @book.body %></p>

 <span>
    <%= link_to "Edit", edit_book_path(@book.id)%>
  </span>
  
  <span>
    <%= link_to "Back", books_path%>
  </span>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%=link_to"start",books_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>